spring.application.name=crudbasico

server.port=${PORT:8090}

# PostgreSQL - Neon
spring.datasource.url=jdbc:postgresql://ep-bold-star-aqecrnjz-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_IeL6s4TgPRka

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect